using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IOData
{
    public static class StPrice
    {
        public static List<string> StkPrices()
        {
            List<string> Obj = new List<string>();

            //  Obj.Add("	ACC	#	20	");
            //  Obj.Add("	ADANIENT	#	10	");
            //  Obj.Add("	ADANIPORTS	#	10	");
            //  Obj.Add("	ADANIPOWER	#	2.50	");
            //  Obj.Add("	AJANTPHARM	#	50	");
            //  Obj.Add("	ALBK	#	2.50	");
            //  Obj.Add("	AMARAJABAT	#	20	");
            //  Obj.Add("	AMBUJACEM	#	5	");
            //  Obj.Add("	ANDHRABANK	#	2.50	");
            //  Obj.Add("	APOLLOHOSP	#	20	");
            //  Obj.Add("	APOLLOTYRE	#	10	");
            //  Obj.Add("	ARVIND	#	10	");
            //  Obj.Add("	ASHOKLEY	#	5	");
            //  // Obj.Add("	ASIANPAINT	#	20	");
            //  Obj.Add("	AUROPHARMA	#	10	");
            Obj.Add("	AXISBANK	#	10	");
            //  Obj.Add("	BAJAJ-AUTO	#	50	");
            //  Obj.Add("	BAJAJFINSV	#	100	");
            //  Obj.Add("	BAJFINANCE	#	50	");
            //  Obj.Add("	BALKRISIND	#	20	");
            //  Obj.Add("	BALRAMCHIN	#	5	");
            //  Obj.Add("	BANKBARODA	#	5	");
            //  //Obj.Add("	BANKINDIA	#	5	");
            //  Obj.Add("	BATAINDIA	#	20	");
            //  Obj.Add("	BEL	#	5	");
            //  Obj.Add("	BEML	#	50	");
            //  Obj.Add("	BERGEPAINT	#	5	");
            //  Obj.Add("	BHARATFIN	#	20	");
            //  Obj.Add("	BHARATFORG	#	20	");
            //  Obj.Add("	BHARTIARTL	#	10	");
            //  Obj.Add("	BHEL	#	2.50	");
            //  Obj.Add("	BIOCON	#	20	");
            //  Obj.Add("	BOSCHLTD	#	250	");
            //  Obj.Add("	BPCL	#	10	");
            //  Obj.Add("	BRITANNIA	#	100	");
            //  Obj.Add("	CADILAHC	#	10	");
            //  Obj.Add("	CANBK	#	10	");
            //  Obj.Add("	CANFINHOME	#	20	");
            //  Obj.Add("	CAPF	#	20	");
            //  Obj.Add("	CASTROLIND	#	5	");
            //  Obj.Add("	CEATLTD	#	50	");
            //  Obj.Add("	CENTURYTEX	#	50	");
            //  Obj.Add("	CESC	#	20	");
            //  Obj.Add("	CGPOWER	#	2.50	");
            //  Obj.Add("	CHENNPETRO	#	10	");
            //  Obj.Add("	CHOLAFIN	#	50	");
            //  Obj.Add("	CIPLA	#	10	");
            //  Obj.Add("	COALINDIA	#	5	");
            //  Obj.Add("	COLPAL	#	20	");
            //  Obj.Add("	CONCOR	#	20	");
            //  Obj.Add("	CUMMINSIND	#	20	");
            //  Obj.Add("	DABUR	#	5	");
            //  Obj.Add("	DALMIABHA	#	100	");
            //  Obj.Add("	DCBBANK	#	5	");
            //  Obj.Add("	DHFL	#	20	");
            //  Obj.Add("	DISHTV	#	2.50	");
            //  Obj.Add("	DIVISLAB	#	20	");
            //  Obj.Add("	DLF	#	10	");
            //  Obj.Add("	DRREDDY	#	50	");
            //  Obj.Add("	EICHERMOT	#	250	");
            //  Obj.Add("	ENGINERSIN	#	5	");
            //  Obj.Add("	EQUITAS	#	5	");
            //  Obj.Add("	ESCORTS	#	20	");
            //  //  Obj.Add("	EXIDEIND	#	5	");
            //  Obj.Add("	FEDERALBNK	#	2.50	");
            //  Obj.Add("	GAIL	#	10	");
            //  Obj.Add("	GLENMARK	#	10	");
            //  Obj.Add("	GMRINFRA	#	2.50	");
            //  // Obj.Add("	GODFRYPHLP	#	20	");
            //  Obj.Add("	GODREJCP	#	20	");
            //  Obj.Add("	GODREJIND	#	10	");
            //  Obj.Add("	GRANULES	#	2.50	");
            //  Obj.Add("	GRASIM	#	20	");
            //  Obj.Add("	GSFC	#	5	");
            //  Obj.Add("	HAVELLS	#	10	");
            //  Obj.Add("	HCC	#	2.50	");
            //  // Obj.Add("	HCLTECH	#	20	");
            //  Obj.Add("	HDFC	#	50	");
            Obj.Add("	HDFCBANK	#	20	");
            //  Obj.Add("	HDIL	#	2.50	");
            //  Obj.Add("	HEROMOTOCO	#	50	");
            //  Obj.Add("	HEXAWARE	#	10	");
            Obj.Add("	HINDALCO	#	5	");
            //  Obj.Add("	HINDPETRO	#	10	");
            //  Obj.Add("	HINDUNILVR	#	20	");
            //  Obj.Add("	HINDZINC	#	10	");
            //  Obj.Add("	IBULHSGFIN	#	50	");
            Obj.Add("	ICICIBANK	#	10	");
            //  Obj.Add("	ICICIPRULI	#	10	");
            //  Obj.Add("	IDBI	#	5	");
            //  //  Obj.Add("	IDEA	#	2.50	");
            //  Obj.Add("	IDFC	#	2.50	");
            //  //  Obj.Add("	IDFCBANK	#	2.50	");
            //  Obj.Add("	IFCI	#	2.50	");
            //  Obj.Add("	IGL	#	10	");
            //  Obj.Add("	INDIACEM	#	5	");
            //  Obj.Add("	INDIANB	#	10	");
            //  Obj.Add("	INDIGO	#	50	");
            Obj.Add("	INDUSINDBK	#	20	");
            //  Obj.Add("	INFIBEAM	#	10	");
            //  Obj.Add("	INFRATEL	#	10	");
            //  Obj.Add("	INFY	#	20	");
            //  Obj.Add("	IOC	#	5	");
            //  Obj.Add("	IRB	#	5	");
            // Obj.Add("	ITC	#	5	");
            //  Obj.Add("	JETAIRWAYS	#	20	");
            //  Obj.Add("	JINDALSTEL	#	10	");
            //  Obj.Add("	JISLJALEQS	#	5	");
            //  Obj.Add("	JPASSOCIAT	#	2.50	");
            //  Obj.Add("	JSWSTEEL	#	10	");
            //  Obj.Add("	JUBLFOOD	#	50	");
            //  Obj.Add("	JUSTDIAL	#	20	");
            //  Obj.Add("	KAJARIACER	#	10	");
            Obj.Add("	KOTAKBANK	#	20	");
            //  Obj.Add("	KPIT	#	10	");
            //  Obj.Add("	KSCL	#	20	");
            //  Obj.Add("	KTKBANK	#	5	");
            //  Obj.Add("	L&TFH	#	5	");
            //  Obj.Add("	LICHSGFIN	#	10	");
            //  Obj.Add("	LT	#	20	");
            //  Obj.Add("	LUPIN	#	20	");
            //  Obj.Add("	M&M	#	20	");
            //  Obj.Add("	M&MFIN	#	10	");
            //  Obj.Add("	MANAPPURAM	#	5	");
            //  Obj.Add("	MARICO	#	5	");
            //  Obj.Add("	MARUTI	#	100	");
            //  Obj.Add("	MCDOWELL-N	#	100	");
            //  Obj.Add("	MCX	#	20	");
            //  Obj.Add("	MFSL	#	10	");
            //  Obj.Add("	MGL	#	20	");
            //  Obj.Add("	MINDTREE	#	20	");
            //  Obj.Add("	MOTHERSUMI	#	10	");
            //  Obj.Add("	MRF	#	250	");
            //  Obj.Add("	MRPL	#	5	");
            //  Obj.Add("	MUTHOOTFIN	#	10	");
            //  Obj.Add("	NATIONALUM	#	2.50	");
            //  Obj.Add("	NBCC	#	2.50	");
            //  Obj.Add("	NCC	#	5	");
            //  Obj.Add("	NESTLEIND	#	100	");
            //  Obj.Add("	NHPC	#	2.50	");
            //  Obj.Add("	NIITTECH	#	50	");
            //  Obj.Add("	NMDC	#	5	");
            //  Obj.Add("	NTPC	#	2.50	");
            //  Obj.Add("	OFSS	#	100	");
            //  Obj.Add("	OIL	#	10	");
            //  Obj.Add("	ONGC	#	5	");
            //  Obj.Add("	ORIENTBANK	#	5	");
            //  Obj.Add("	PAGEIND	#	250	");
            //  Obj.Add("	PCJEWELLER	#	50	");
            //  Obj.Add("	PEL	#	50	");
            //  Obj.Add("	PETRONET	#	5	");
            //  Obj.Add("	PFC	#	2.50	");
            //  Obj.Add("	PIDILITIND	#	20	");
            // Obj.Add("	PNB	#	5	");
            // Obj.Add("	POWERGRID	#	2.50	");
            //  Obj.Add("	PTC	#	2.50	");
            //  Obj.Add("	PVR	#	50	");
            //  Obj.Add("	RAMCOCEM	#	20	");
            //  Obj.Add("	RAYMOND	#	50	");
            //  Obj.Add("	RBLBANK	#	10	");
            //  Obj.Add("	RCOM	#	2.50	");
            //  Obj.Add("	RECLTD	#	5	");
            //  Obj.Add("	RELCAPITAL	#	20	");
            //  Obj.Add("	RELIANCE	#	20	");
            //  Obj.Add("	RELINFRA	#	20	");
            //  Obj.Add("	REPCOHOME	#	20	");
            //  Obj.Add("	RNAVAL	#	2.50	");
            //  Obj.Add("	RPOWER	#	2.50	");
            //Obj.Add("SAIL#2.50");
            Obj.Add("SBIN#5");
            //  Obj.Add("	SHREECEM	#	250	");
            //  Obj.Add("	SIEMENS	#	20	");
            //  Obj.Add("	SOUTHBANK	#	2.50	");
            //  Obj.Add("	SREINFRA	#	2.50	");
            //  Obj.Add("	SRF	#	50	");
            //  Obj.Add("	SRTRANSFIN	#	50	");
            //  Obj.Add("	STAR	#	20	");
            //  Obj.Add("	SUNPHARMA	#	20	");
            //  Obj.Add("	SUNTV	#	20	");
            //  Obj.Add("	SUZLON	#	2.50	");
            //  Obj.Add("	SYNDIBANK	#	2.50	");
            //  Obj.Add("	TATACHEM	#	20	");
            //  Obj.Add("	TATACOMM	#	10	");
            //  Obj.Add("	TATAELXSI	#	20	");
            Obj.Add("	TATAGLOBAL	#	10	");
            //  Obj.Add("	TATAMOTORS	#	10	");
            //  Obj.Add("	TATAMTRDVR	#	5	");
            //  Obj.Add("	TATAPOWER	#	2.50	");
            Obj.Add("	TATASTEEL	#	20	");
            //  Obj.Add("	TCS	#	50	");
            //  Obj.Add("	TECHM	#	10	");
            //  Obj.Add("	TITAN	#	20	");
            //  Obj.Add("	TORNTPHARM	#	20	");
            //  Obj.Add("	TORNTPOWER	#	10	");
            //  Obj.Add("	TV18BRDCST	#	2.50	");
            //  Obj.Add("	TVSMOTOR	#	20	");
            //  Obj.Add("	UBL	#	50	");
            /// Obj.Add("	UJJIVAN	#	10	");
            //  Obj.Add("	ULTRACEMCO	#	100	");
            // Obj.Add("	UNIONBANK	#	5	");
            //  Obj.Add("	UPL	#	20	");
            Obj.Add("	VEDL	#	10	");
            //  Obj.Add("	VGUARD	#	10	");
            //  Obj.Add("	VOLTAS	#	20	");
            //  Obj.Add("	WIPRO	#	5	");
            //  Obj.Add("	WOCKPHARMA	#	20	");
            Obj.Add("	YESBANK	#	10	");
            //  Obj.Add("	ZEEL	#	10	");
            return Obj;
        }
    }
}
